(function (global) {
  global.ToolboxTools = [
    {
      id: "scoreboard",
      name: "打牌计分板",
      desc: "胜负分数记录",
      category: "效率",
      icon: "±",
      theme: "theme-indigo",
      url: "#/tools/scoreboard",
      component: global.ScoreboardTool,
      enabled: true,
    },
    {
      id: "lucky-wheel",
      name: "幸运转盘",
      desc: "自定义抽奖",
      category: "效率",
      icon: "◎",
      theme: "theme-orange",
      badge: "New",
      url: "#/tools/lucky-wheel",
      component: global.LuckyWheelTool,
      enabled: true,
    },
    {
      id: "fruit-puzzle",
      name: "果果拼拼乐",
      desc: "果蔬认知拼图",
      category: "亲子",
      icon: "果果",
      theme: "theme-green",
      badge: "New",
      url: "#/tools/fruit-puzzle",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "star-isle-guard",
      name: "西游星球",
      desc: "召唤合成萌系塔防",
      category: "游戏",
      icon: "星屿",
      theme: "theme-blue",
      badge: "New",
      url: "#/tools/star-isle-guard",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "sliding-puzzle",
      name: "数字华容道",
      desc: "3×3 至 10×10 挑战",
      category: "游戏",
      icon: "15",
      theme: "theme-red",
      badge: "New",
      url: "#/tools/sliding-puzzle",
      component: global.SlidingPuzzleTool,
      enabled: true,
    },
    {
      id: "core-breach-game",
      name: "弹壳打工",
      desc: "竖屏割草生存",
      category: "游戏",
      icon: "弹壳",
      theme: "theme-green",
      badge: "New",
      url: "#/tools/core-breach-game",
      component: global.CoreBreachGameTool,
      enabled: true,
    },
    {
      id: "core-breach-legacy",
      name: "花园防线",
      desc: "明亮花园策略塔防",
      category: "游戏",
      icon: "花园",
      theme: "theme-green",
      badge: "经典",
      url: "#/tools/core-breach-legacy",
      component: global.LegacyCoreBreachGameTool,
      enabled: true,
    },
    {
      id: "abyss-salvage",
      name: "深渊采样",
      desc: "深海搜集生存",
      category: "游戏",
      icon: "深潜",
      theme: "theme-cyan",
      badge: "New",
      url: "#/tools/abyss-salvage",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "wasteland-convoy",
      name: "荒原车队",
      desc: "废土公路追逐",
      category: "游戏",
      icon: "车队",
      theme: "theme-orange",
      badge: "New",
      url: "#/tools/wasteland-convoy",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "sky-bastion",
      name: "天穹守望",
      desc: "弹道防空拦截",
      category: "游戏",
      icon: "天穹",
      theme: "theme-blue",
      badge: "New",
      url: "#/tools/sky-bastion",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "shadow-infiltration",
      name: "影域潜行",
      desc: "节点潜行破解",
      category: "游戏",
      icon: "影域",
      theme: "theme-green",
      badge: "New",
      url: "#/tools/shadow-infiltration",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "core-forge",
      name: "熔核锻造",
      desc: "四色节奏锻造",
      category: "游戏",
      icon: "熔核",
      theme: "theme-red",
      badge: "New",
      url: "#/tools/core-forge",
      component: global.ArcadeGameTool,
      enabled: true,
    },
    {
      id: "aabb-box",
      name: "AABB 盒子",
      desc: "碰撞框计算",
      category: "开发",
      icon: "▣",
      theme: "theme-blue",
      badge: "New",
      url: "#/tools/aabb-box",
      component: global.AabbBoxTool,
      enabled: true,
    },
    {
      id: "json-format",
      name: "JSON 格式化",
      desc: "压缩与校验",
      category: "开发",
      icon: "{ }",
      theme: "theme-green",
      url: "#/tools/json-format",
      component: global.JsonFormatTool,
      enabled: true,
    },
    {
      id: "color-picker",
      name: "颜色取样",
      desc: "HEX 与 RGB",
      category: "设计",
      icon: "◐",
      theme: "theme-pink",
      url: "#/tools/color-picker",
      component: global.ColorPickerTool,
      enabled: true,
    },
    {
      id: "palette-maker",
      name: "色板生成",
      desc: "主色配色方案",
      category: "设计",
      icon: "◆",
      theme: "theme-pink",
      url: "#/tools/palette-maker",
      component: global.PaletteMakerTool,
      enabled: true,
    },
    {
      id: "gradient-maker",
      name: "渐变生成",
      desc: "CSS 渐变预览",
      category: "设计",
      icon: "↗",
      theme: "theme-orange",
      url: "#/tools/gradient-maker",
      component: global.GradientMakerTool,
      enabled: true,
    },
    {
      id: "shadow-radius",
      name: "阴影圆角",
      desc: "卡片样式调试",
      category: "设计",
      icon: "▢",
      theme: "theme-gray",
      url: "#/tools/shadow-radius",
      component: global.ShadowRadiusTool,
      enabled: true,
    },
    {
      id: "image-compress",
      name: "图片压缩",
      desc: "裁剪与压缩",
      category: "图片",
      icon: "▧",
      theme: "theme-orange",
      url: "#/tools/image-compress",
      component: global.ImageCompressTool,
      enabled: true,
    },
    {
      id: "unit-convert",
      name: "单位换算",
      desc: "长度面积体积",
      category: "生活",
      icon: "↔",
      theme: "theme-cyan",
      url: "#/tools/unit-convert",
      component: global.UnitConvertTool,
      enabled: true,
    },
    {
      id: "date-calc",
      name: "日期计算",
      desc: "间隔与倒数",
      category: "生活",
      icon: "□",
      theme: "theme-gray",
      url: "#/tools/date-calc",
      component: global.DateCalcTool,
      enabled: true,
    },
    {
      id: "random",
      name: "随机生成",
      desc: "参数 JSON",
      category: "开发",
      icon: "#",
      theme: "theme-red",
      url: "#/tools/random",
      component: global.RandomGeneratorTool,
      enabled: true,
    },
    {
      id: "jwt-decode",
      name: "JWT 解析",
      desc: "Token 解码校验",
      category: "开发",
      icon: "JW",
      theme: "theme-indigo",
      url: "#/tools/jwt-decode",
      component: global.JwtDecodeTool,
      enabled: true,
    },
    {
      id: "base64-codec",
      name: "Base64",
      desc: "编码与解码",
      category: "开发",
      icon: "64",
      theme: "theme-blue",
      url: "#/tools/base64-codec",
      component: global.Base64CodecTool,
      enabled: true,
    },
    {
      id: "url-query",
      name: "URL 参数",
      desc: "Query 转 JSON",
      category: "开发",
      icon: "?=",
      theme: "theme-green",
      url: "#/tools/url-query",
      component: global.UrlQueryTool,
      enabled: true,
    },
    {
      id: "regex-test",
      name: "正则测试",
      desc: "匹配与分组",
      category: "开发",
      icon: ".*",
      theme: "theme-red",
      url: "#/tools/regex-test",
      component: global.RegexTestTool,
      enabled: true,
    },
    {
      id: "todo-list",
      name: "待办清单",
      desc: "轻量任务记录",
      category: "效率",
      icon: "☑",
      theme: "theme-green",
      url: "#/tools/todo-list",
      component: global.TodoListTool,
      enabled: true,
    },
    {
      id: "pomodoro",
      name: "番茄计时",
      desc: "专注与休息",
      category: "效率",
      icon: "25",
      theme: "theme-red",
      url: "#/tools/pomodoro",
      component: global.PomodoroTool,
      enabled: true,
    },
    {
      id: "teleprompter",
      name: "提词器",
      desc: "全屏滚动文稿",
      category: "效率",
      icon: "词",
      theme: "theme-indigo",
      url: "#/tools/teleprompter",
      component: global.TeleprompterTool,
      enabled: true,
    },
    {
      id: "text-dedupe",
      name: "文本去重",
      desc: "行处理排序",
      category: "效率",
      icon: "≡",
      theme: "theme-cyan",
      url: "#/tools/text-dedupe",
      component: global.TextDedupeTool,
      enabled: true,
    },
    {
      id: "notes",
      name: "速记便签",
      desc: "临时记录",
      category: "效率",
      icon: "✎",
      theme: "theme-gray",
      url: "#/tools/notes",
      component: global.NotesTool,
      enabled: true,
    },
  ];
})(window);
