(function (global) {
  global.ToolboxTools = [
    {
      id: "scoreboard",
      name: "打牌计分板",
      desc: "胜负分数记录",
      category: "效率",
      icon: "±",
      theme: "theme-indigo",
      badge: "New",
      url: "#/tools/scoreboard",
      component: global.ScoreboardTool,
      enabled: true,
    },
    {
      id: "aabb-box",
      name: "AABB 盒子",
      desc: "碰撞框计算",
      category: "开发",
      icon: "▣",
      theme: "theme-blue",
      badge: "New",
      url: "#/tools/aabb-box",
      enabled: true,
    },
    {
      id: "json-format",
      name: "JSON 格式化",
      desc: "压缩与校验",
      category: "开发",
      icon: "{ }",
      theme: "theme-green",
      url: "#/tools/json-format",
      enabled: true,
    },
    {
      id: "color-picker",
      name: "颜色取样",
      desc: "HEX 与 RGB",
      category: "设计",
      icon: "◐",
      theme: "theme-pink",
      url: "#/tools/color-picker",
      enabled: false,
    },
    {
      id: "image-compress",
      name: "图片压缩",
      desc: "本地轻量处理",
      category: "图片",
      icon: "▧",
      theme: "theme-orange",
      url: "#/tools/image-compress",
      enabled: false,
    },
    {
      id: "unit-convert",
      name: "单位换算",
      desc: "长度面积体积",
      category: "生活",
      icon: "↔",
      theme: "theme-cyan",
      url: "#/tools/unit-convert",
      enabled: false,
    },
    {
      id: "date-calc",
      name: "日期计算",
      desc: "间隔与倒数",
      category: "生活",
      icon: "□",
      theme: "theme-gray",
      url: "#/tools/date-calc",
      enabled: false,
    },
    {
      id: "random",
      name: "随机生成",
      desc: "数字与密码",
      category: "效率",
      icon: "#",
      theme: "theme-red",
      url: "#/tools/random",
      enabled: false,
    },
    {
      id: "notes",
      name: "速记便签",
      desc: "临时记录",
      category: "效率",
      icon: "✎",
      theme: "theme-gray",
      url: "#/tools/notes",
      enabled: false,
    },
  ];
})(window);
